-- CEO 2026-08-21: audit "bên Booqable còn SP nào chưa qua CRM không" tìm ra
-- 179 sản phẩm thật (loại bỏ noise/EOL) chưa có trong CRM mới. CEO duyệt
-- nhập theo từng nhóm, đã áp hết qua REST service-role — file này là sổ
-- sách. Giá/cọc/tồn kho LẤY THẬT từ Booqable (API + trang inventory từng
-- sản phẩm), KHÔNG bịa số.
--
-- Mọi equipment_types tạo mới đều dùng pricing_template_id
-- '88a44846-ec1d-46bb-b508-09d5c5f60a78', pricing_method='pricing_structure',
-- rental_period_unit='day', product_type='rental'. Sản phẩm 0 tồn kho thật
-- vẫn tạo type (CEO nhập serial sau khi có hàng), theo đúng tiền lệ đã dùng
-- cho Xbox Series S / Cục phát 5G WiFi 7 AI-tier.
--
-- ## Gaming (2 SP, CEO liệt kê riêng trước đợt lớn)
--   * Vô lăng Logitech Driving Force G29 72c2bedf-e45f-4d82-be0a-da7306532e95
--     — quantity, tồn thật HN2+HCM2=4
--   * Máy chơi games Microsoft Xbox Series S 73b1a24c-478d-4645-b3cc-fce1f077772b
--     — individual, 0 tồn thật hiện tại
--
-- ## Âm thanh (18 SP — "Âm thanh (loa/mic/mixer) nhập hết dùm tao")
--   Amply Harman Kardon HK 3700, Apple HomePod (3 serial thật j12dfi/f6hhol/
--   leotu4), Apple HomePod 2, Astell & Kern AK380 (0 tồn), Braven XXL (0 tồn),
--   Bộ micro Excelvan, Cho thuê Loa Bose Soundlink Revolve Plus II (0 tồn,
--   biến thể Đen/Trắng), Deity Pocket Wireless, Megaphone TOA ER-2215,
--   SARAMONIC Blink500 B4 (serial thật), Soundmax MC-01, AKG ARA C22-USB,
--   Microphone Hội Nghị, K&F WM10, Platinum KS-5000, Saramonic SmartRig+
--   (serial thật), Vang số ACNOS Mi30s, Loa Harman Kardon Soundstick 4 (0 tồn).
--   Lưu ý: chạy lỡ script 2 lần tạo trùng 18 dòng, CEO xác nhận xoá — đã dọn.
--
-- ## Laptop / PC / Workstation (17 SP)
--   Dell Latitude 5490/5570/7470/7480/E7470, HP Workstation ZBook 15 G4,
--   Laptop Acer NITRO 5, Laptop i5 11th (0 tồn), Lenovo X1 Carbon Gen 3/Gen 8,
--   Lenovo X1 i5 8GB, Lenovo Yoga C740 (0 tồn), Mac Studio M1 MAX (0 tồn),
--   Bộ Mini PC i5 Gen 6 (HN20+HCM20), Máy miniPC HP 800 G2 (34 serial thật),
--   PC i5 Gen 10 (0 tồn), Dell Vostro 3550.
--
-- ## Lặt vặt: Kính/Wacom/Máy chiếu/DJ+office/Drone-gimbal/Đèn (18 SP)
--   Rokid Glasses (0 tồn), Xreal BEAM, Wacom Intuos Pro (0 tồn), Màn chiếu
--   120 inch (0 tồn), Optoma PS3166 (0 tồn), Xiaomi Projector L1 (0 tồn),
--   Pioneer DJ XDJ-RX2 (0 tồn), Bộ lưu điện 5V 650VA UPS (32 serial thật),
--   HP LaserJet Pro MFP 135W (0 tồn), Sunmi T1 POS (4 serial), Đầu đĩa than
--   TEAC TN-180BT-A3 (0 tồn), DJI SDR Transmission Combo (0 tồn), Movmax
--   Blade ARM (0 tồn), Đèn Aputure LS300X/amaran 200X/amaran 300x (0 tồn),
--   Đèn Livestream 33cm, Đèn quay phim YOUGNO (3 serial).
--
-- ## Đồng hồ thông minh (11 SP)
--   Garmin Enduro, Epix Gen 2, Fenix 6S Sapphire (0 tồn), Vivoactive 3 (3
--   serial), Apple Watch Series 7/8/9/10/11 (0 tồn), Apple Watch Ultra 3
--   (0 tồn), Samsung Galaxy Watch 6 LTE (0 tồn).
--
-- ## Camera / webcam 360 (15 SP)
--   Camera IP IMOU (0 tồn), Matterport Axis (3 serial), Leica Q1/Q2/Q3
--   (0 tồn — giá rất cao, CEO xác nhận đúng theo Booqable), OBSBOT Tiny,
--   Ricoh THETA SC2 (0 tồn)/V/Z1/M15, Samsung Gear 360 (2017)/thường, Sony
--   RX100 mark V, Sony ZV-E10 (3 serial HN1+HCM2), Webcam Poly Studio P15
--   4K (0 tồn).
--
-- Danh sách đầy đủ id + tên: xem lịch sử REST trong phiên làm việc
-- 2026-08-21 (không lưu lại toàn bộ id ở đây vì quá dài — tra theo tên
-- trong equipment_types nếu cần).

-- ## Chuyển sang theo dõi serial (quản lý theo từng máy)
--   * Ổ cứng di động SSD 1TB ca7c0874-557a-42bc-9028-7e8ecfff7767 — tồn thật
--     Booqable 7 máy (HN3 Samsung T7 Shield + HCM1 Samsung T7 Shield + HCM3
--     KIOXIA), serial mã AUTO-SSD1TB-*. equipment_units/stock cũ (KIOXIA/
--     Samsung T7 Shield/Lacie 1TB — số ảo) GIỮ NGUYÊN không xoá, chỉ không
--     dùng nữa.
--   * DJI Mic 1 (2 TX 1 RX) 2463d322-1212-4baf-8a71-3b59a8e88ac8 — tồn thật
--     HN3+HCM3=6, serial AUTO-DJIMIC1-*.
--   * DJI Mic 3 - 2TX + 1RX c639239f-bd47-4951-977b-faa1ffa9cff1 — tồn thật
--     (chỉ tính biến thể 2TX+1RX, bỏ biến thể 1TX riêng) HN1+HCM5=6, serial
--     AUTO-DJIMIC3-*.
--   * DJI Mic Mini 2 (2 TX) 01a86360-18ba-4f37-ae1e-2ff0fefc9c15 — tồn thật
--     HN3+HCM6=9, serial AUTO-DJIMICMINI2-*.
--   Lưu ý: một số dòng order_equipment CŨ (đơn đã "nhap_kho_bao_tri" — lịch
--   sử đóng) vẫn gắn equipment_unit_id kiểu số lượng cũ — theo đúng tiền lệ
--   WiFi6/7 (20260819070000), KHÔNG động vào lịch sử cũ, chỉ vỡ nếu sau này
--   sửa lại đúng dòng đó.

-- ## Đối chiếu tồn kho thật theo yêu cầu CEO (EOL/[KHÔNG DÙNG] = SP CRM)
--   * Cục phát 4G 8bdbb7dc-4489-42c5-9c66-d503b0ed0fcd (EOL-WF) — tồn thật 7,
--     toàn bộ TP HCM.
--   * Loa trợ giảng 2791e4f3-6a4e-4385-9f56-0e0dcbc15254, biến thể STARGO —
--     tồn thật 24 (HN14+HCM10, trước đó CRM ghi 34 số ảo); biến thể TAKSTAR
--     — tồn thật 1 (HCM, trước đó CRM ghi 32 số ảo).
--   * Nintendo Switch 146a1730-f790-4887-8de9-38e16cac50db (EOL SW) — thêm 7
--     serial thật NSW-01..07 (HN2+HCM5).
--   * iPad Pro M2 11 inch 90603585-9453-4d3a-bba7-d90290a0c8d1 (EOL M2 11) —
--     thêm 1 serial thật IPAD_PRO_11_INCH_M2-1 (HN).
--   * Kiểm 0 tồn thật, không cần làm gì thêm: EOL 43-inch/TV 4K 43 inch,
--     EOL 02/iPad Pro M2 11 inch (2 mã EOL trỏ cùng 1 SP), EOL 14PRO/iPhone
--     14 Pro, EOL YESOUL/Máy tập đạp xe YESOUL M1, EOL 000/Xe Scooter Điện
--     NINEBOT18W, EOL 06/iPad Pro M1 12.9in, EOL MBDP/Màn Hình Di Động,
--     EOL IP11PRO/iPhone 11 Pro, EOL 03/iPad Pro M1 11in, EOL 12 + EOL 13/
--     iPad Air 4 10.9in (2 mã cùng 1 SP), [EOL] iPhone 11/iPhone 11.
--
-- ## Đối chiếu "lịch sử thuê" của các mã EOL/[KHÔNG DÙNG] (CEO 2026-08-21):
--   CEO lo các đơn thuê cũ của 18 SP đã xoá bên Booqable (Cục phát 4G, Loa
--   trợ giảng STARGO/TAKSTAR, TV4K43, iPad Pro M2 11in, iPhone 14 Pro,
--   YESOUL M1, Xe Scooter NINEBOT18W, iPad Pro M1 12.9in, Màn Hình Di Động,
--   iPhone 11 Pro, Nintendo Switch, iPad Air 4 10.9in, iPhone 11, DJI Osmo
--   Action 1, Playstation 5 kèm 2 tay cầm) bị mất khỏi CRM. Đối chiếu 266
--   dòng đơn lịch sử (2021-2026, lấy qua Booqable API product_trackers +
--   order lines thật) với 265 đơn CRM tương ứng (order_code = BQ{số đơn
--   Booqable}) — KẾT QUẢ: cả 266 dòng đã có sẵn trong CRM từ đợt seed gốc,
--   được khớp thẳng vào equipment_type SỐNG hiện tại (không phải mã EOL đã
--   xoá) ngay từ đầu. Không có dữ liệu nào thực sự bị thiếu — không insert
--   thêm gì. Có 1 dòng test thủ công (Cục phát 4G, đơn BQ1008) bị lỡ tạo
--   trùng trong lúc dò cấu trúc bảng, đã xoá lại ngay sau khi phát hiện.
--
-- ## Quét TOÀN BỘ 34 mã EOL/OEL Booqable (CEO 2026-08-21 đợt 2 — "lịch sử
--    cho thuê phải chính xác xuyên suốt dù đổi tên"):
--   547 đơn lịch sử duy nhất (2020-2026). Kết quả & việc đã làm qua REST:
--   * 543/547 đơn đã có sẵn + dòng gắn đúng SP sống (kể cả các map CEO đưa
--     thêm: EOL01→GoPro Media Mod, EOL111→K&F WM10, EOLBODAM→Bộ đàm Xiaomi,
--     [EOL] MBA M2 16GB→MacBook Air M2 16GB, [EOL] MacBook Air M1→MacBook
--     Air M1 (tự tách đúng biến thể 8GB/16GB theo tiêu đề dòng gốc),
--     LG UltraFine + Samsung The Space→Màn hình 4K 32-inch, Marshall
--     Kilburn 2, Seeone S901→Loa trợ giảng, Smart TV 75→TV 4k 75-inch,
--     [EOL] RC→Xe điều khiển RC, EOL13→MacbooK Pro i5 8GB).
--   * 47 dòng "[KHÔNG DÙNG ] OEL DJIMIC" nằm dạng DÒNG TỰ DO (seed không
--     match được tên) → gắn lại vào DJI Mic 1 (2 TX 1 RX) 2463d322…, mỗi
--     dòng 1 instance AUTO-HIST-DJIMIC1-* (disposed); 3 dòng qty>1 tách
--     thành từng dòng riêng (ràng buộc theo dõi riêng lẻ).
--   * BQ12087 thiếu dòng PS5 (0đ, qty 2 — đi kèm ghế lái giả lập) → thêm.
--   * BQ12378 (15-17/08/2026, sau mốc seed) thiếu NGUYÊN ĐƠN → tạo đủ:
--     khách Phạm Đức Nam Anh, PS5 400k + 2 DualSense 200k + ship 150k,
--     10 khâu + đóng đơn, chưa thanh toán (công nợ 750k).
--   * BQ37 + BQ40 (12/2020-03/2021, TRƯỚC mốc seed) thiếu NGUYÊN ĐƠN →
--     tạo đủ: Zakarya Aghbal thuê Samsung The Space (map về Màn hình 4K
--     32-inch), 1.5tr/đơn đã trả đủ, kèm order_payments.
--   * SÁP NHẬP: "Mic không dây K&F WM10" (bb681832…, SP cũ seed) gộp vào
--     "Microphone không dây K&F WM10" (cadb1207…, nhập Booqable hôm nay,
--     kho thật HN5+HCM5) theo lệnh CEO — 7 dòng đơn cũ + website_products
--     (slug thue-mic-khong-day-k-f-wm10) chuyển sang, xoá type/unit/stock cũ.
--   * EOL001: CEO xác nhận lại là Zoom H4N (không phải H6) — 2 đơn lịch
--     sử BQ2809/BQ2922 đã gắn đúng SP Zoom H4N từ đầu, giữ nguyên.
--   * Ghi chú ngoài phạm vi EOL: 231 dòng tự do khác (thẻ game NSW/PS,
--     "[ KHÔNG DÙNG ] JC", MacBook Pro 14 M2...) thuộc SP chưa nhập CRM.
--   * GIẢM GIÁ CẤP ĐƠN (CEO duyệt 2026-08-21): 78 đơn seed cũ ghi giá GỐC
--     trong khi Booqable có giảm giá cấp đơn → thêm vào mỗi đơn 1 dòng tự
--     do "Giảm giá (khớp Booqable)" giá trị ÂM (giữ nguyên dòng thiết bị
--     gốc, trigger tự tính lại total_value). Tổng giảm 78.597.409đ trải
--     2021-2026, đậm nhất 2 khách thuê định kỳ SIGMA (~373k/đơn × ~20 đơn)
--     và Mặt Tiền Á Châu (1.080k/đơn × ~20 đơn). Kiểm lại sau khi áp:
--     78/78 đơn khớp đúng grand_total Booqable.
--
-- ## Đợt gắn lại DÒNG TỰ DO toàn CRM (CEO 2026-08-21 đợt 3):
--   Phát hiện 3.600 dòng order_equipment không gắn SP (equipment_type_id
--   null, 833 tên) trên TOÀN CRM — pattern seed cũ: SP Booqable không match
--   được tên CRM thì để dòng tự do mang tên SP lúc seed. Đã xử lý:
--   * Map CEO chỉ định từng tên (PATCH giữ nguyên giá trị; SP theo dõi
--     riêng lẻ thì tách dòng theo SL + instance AUTO-HIST-* disposed):
--     "[KHÔNG DÙNG] " (PRO_M2_11) 4 dòng→iPad Pro M2 11; "[KHÔNG DÙNG]"
--     (PENCIL 1) 12 dòng→Apple Pencil 1; TMK22CAM 5 dòng→GoWithMe 22-inch
--     màu TRẮNG; "{Không dùng} 4G" 103 dòng→Cục phát 4G; "[KHÔNG DÙNG] KS"
--     16 dòng→Máy Chạy Bộ KingSmith (unit R1 PRO); "[ KHÔNG DÙNG ] JC" 49
--     dòng/74 cặp→Nintendo JoyCon Controllers; "[KHÔNG DÙNG] DS" 150 dòng→
--     Tay cầm PS4 DUALSHOCK; "[KHÔNG DÙNG} DS" 77 dòng→Tay cầm DualSense;
--     "[KHONG DUNG} S20" 21 dòng/66 máy→TẠO MỚI equipment_type "Samsung
--     Galaxy S20" (individual, 400k/cọc 2tr theo Booqable); "[KHÔNG DÙNG]
--     Ổ cứng - Blue/Beige" 19 dòng→SSD 1TB (ghi chú T7 Shield); "[KHÔNG SỬ
--     DỤNG ] Q3" 4 dòng→Meta Quest 3; "[ KHÔNG DÙNG] KTTA SONY" 8 dòng→
--     PlayStation VR2; "[KHONG SU DUNG] S22U" 7 dòng→Samsung S22 Ultra;
--     "[KHÔNG DÙNG]  SLD - Black" 17 dòng→Tai Nghe Bluetooth Chụp Tai
--     (Soul Ultra Đen); "Máy chơi games Xbox + Kinect" 3 dòng→Xbox+Kinect.
--   * Kiểm không cần sửa (đã gắn đúng từ seed): TAB9, iP12, IPADPRO129M2,
--     IPPROM111, IPPROm211, GF65 (40 đơn), ACER4K (23 đơn), T7S 4T, Go9-12
--     BLK, MX T70.
--   * Auto-gắn theo tên khớp chính xác SP CRM: +329 dòng (164 individual +
--     165 quantity, 0 lỗi) — gồm các SP vừa nhập hôm nay (Sony ZV-E10,
--     RX100, Dell E7470, Latitude 5570...).
--   * CÒN LẠI 722 tên / ~2.594 dòng / ~2,6 tỷ chờ CEO map — bảng tra cứu:
--     artifact "Dòng Tự Do Chờ Map" (claude.ai/code, 21/08/2026). Đáng kể:
--     [KHÔNG DÙNG] KS 2 (52tr — nghi là KingSmith R2), [KHONGDUNG} 58i,
--     [KHONGDUNG} 43 HD Xiaomi, [KHONGDUNG] PC i5 12400F, Màn hình
--     DHI-LM22-B200, thẻ game NSW/PS đã nghỉ kinh doanh.
--
-- ## Đợt map tiếp theo (CEO 2026-08-21 đợt 4, xử lý liền tay từng mã):
--   * Gắn thêm: "[ Không dùng mã này  ] G331" 28 dòng/136 tai→Tai nghe
--     Logitech G331; "[KHÔNG DÙNG] KS 2" 38 dòng/52,3tr→KingSmith unit R2
--     (KS đợt trước nằm unit R1 PRO — lịch sử 2 đời máy tách đúng);
--     "NSW V1 ( KHÔNG DÙNG MÃ NÀY )" 22 dòng/20,4tr→Nintendo Switch.
--   * SÁP NHẬP SP trùng: "Ổ cứng di động SSD 2TB - Samsung T7 Shield"
--     5eabc062… gộp vào "Ổ cứng di động SSD 2TB" 0a1bcceb… biến thể T7
--     Shield (unit b4211cac…) — 35 dòng đơn chuyển (kèm 27 đơn lịch sử
--     mã Booqable "[KHÔNG DÙNG] T7 Shield 2TB", verify 27/27), kho cộng
--     dồn HN15(+1 đang thuê)/HCM12/DN14, đóng băng cọc đơn mở BQ12033
--     (2tr, giá trị không đổi vì 2 SP cùng cọc), xoá type/unit/stock cũ.
--     Trang web cũ thue-o-cung-di-dong-ssd-2tb-samsung-t7-shield bị xoá
--     theo FK cascade — URL đó 404, SP đích vẫn còn trang riêng.
--   * Kiểm đã gắn đúng từ seed (không cần sửa): Pencil 2 (19/19 đơn),
--     GG CC/Chromecast, Go9→HERO9, "[ KHÔNG DÙNG SP NÀY] PS5" (96 đơn→
--     PS5 kèm 2 tay cầm), IP9 (65 đơn→iPad Gen 9 10.2-inch).
--
-- ## Đợt map 5 (CEO 2026-08-21, tiếp):
--   * TẠO MỚI + gom lịch sử: "Màn Hình Gaming 1080P 24 inch 165Hz"
--     (serial, 250k/cọc 0, 5 serial thật G24F-* đã nghỉ; gom 45 dòng/71
--     chiếc từ 3 tên: mã 24F-EK + biến thể Gigabyte + biến thể ASUS TUF);
--     "PC Core i5 14th 32GB RAM RTX 3080" (số lượng, 1tr/cọc 5tr, kho
--     thật HN2+HCM1; gom 13 dòng/17 máy/53,15tr); "iMac 5K 27 inch 2019"
--     (serial, 800k/cọc 5tr, serial thật C02C90Z7JV3Q; 14 dòng/47,3tr);
--     "iMac 5K 27 inch 2015" (serial, 600k/cọc 5tr, serial IMAC_27-1/2;
--     4 dòng/4,3tr).
--   * Gom vào SP có sẵn: "[KHONGDUNG} 58i" 33 dòng/43 TV/53tr→TV 4k 58
--     inch (ghi chú Xiaomi); "[KHÔNG DÙNG] Màn hình DHI-LM22-B200" 8
--     dòng/67 chiếc/25,4tr→Màn Hình 1080P 22 inch; MacBook Pro M1 Pro
--     16 inch 1 dòng 4,8tr. "IM27 - 2012" ban đầu dồn vào iMac 2017
--     nhưng CEO đổi ý → TẠO RIÊNG "iMac 27 inch 2012" (serial, 500k/cọc
--     5tr, serial thật IMAC_27-LAMND; 4 dòng/4 máy/3,52tr đã chuyển sang).
--   * GIẢI TÁN SP BỘ: "Bộ Mini PC i5 Gen 6 + màn 22inch" (tạo sáng nay)
--     tách 2 dòng lịch sử (23,4tr + 900k) thành dòng Mini PC i5 6th +
--     Màn Hình 1080P 22 inch theo tỷ lệ giá chuẩn 200k:150k (tổng đơn
--     không đổi), kho 40 bộ cộng +20HN+20HCM vào TỪNG SP con, xoá SP bộ.
--   * Kiểm đã gắn đúng từ seed: Tay cầm Xbox Wireless Controller,
--     MacBook Pro M3 Pro 36GB 16 inch (18/18 đơn).
--
-- ## Đợt map 6 (CEO 2026-08-21, tiếp):
--   * Gom vào SP có sẵn: MacBook Pro 14 M2 PRO 32GB 15 dòng/44,1tr→
--     MacBook Pro M2 Pro 32GB RAM 14 inch; "[KHONGDUNG}  43 HD" 47 dòng/
--     64 TV/62,3tr→Smart TV 1080p 43 inch (đủ 4 biến thể Xiaomi/Sharp/
--     COCA×2 + 1 Sony 43X75K, ghi chú đúng từng biến thể); "[KHONGDUNG]
--     PC - i5 12400F" 10 dòng/21 máy/25,6tr→PC Core i5 12th 32GB RTX 3060
--     (2 biến thể i7 12700F + i7 14700 chờ CEO gật); Mac Mini M1 8GB 49
--     dòng/52 máy/71,5tr→Mac Mini M1 8GB RAM; MacBook Air 13.3 M1 39
--     dòng lẻ→tách 32 máy 16GB + 7 máy 8GB theo RAM trong tên (8 dòng
--     tên trần không ghi RAM → 16GB theo map gốc CEO); "Smart TV 4K
--     58-inch - XIAOMI_A2" 14 dòng/18 TV/22,4tr→TV 4k 58 inch.
--   * TẠO MỚI: "Laptop 14inch i5 8th 8GB 256GB SSD" (SP xoá hẳn khỏi
--     Booqable — giá tạm 200k theo mức phổ biến lịch sử, cọc 0, kho 0;
--     20 dòng/110 máy/45,4tr); "Mac Studio M1 Max 64GB RAM" (Booqable
--     sống: 1tr/cọc 15tr, kho HCM1; 6 dòng/25,3tr); "Mac Mini M2 16GB
--     RAM 256GB SSD" (SP xoá hẳn — giá/cọc mượn chuẩn Mac Mini M1 16GB
--     400k/5tr; 9 dòng/24,5tr); "Saramonic WiTalk9 Full-Duplex Wireless
--     Intercom System" (200k/cọc 200k, kho HN10); "Quạt Không Cánh"
--     (400k/cọc 1tr, kho HCM11; 10 dòng/44 chiếc/24,4tr).
--   * MÁY ĐỀ XUẤT cho 688 tên còn lại (CEO quá tải, yêu cầu tự quét +
--     đề xuất): so khớp tên cũ ↔ SP CRM, luật chặt "tên đích nằm trọn
--     trong tên cũ" mới coi là chắc chắn. Kết quả: 66 tên chắc chắn
--     (443tr) + 317 cần chọn (1,08 tỷ) + 250 không có SP (125tr) + 55
--     bỏ qua (151tr — thẻ game/phí phạt/dòng chung). Artifact "Đề Xuất
--     Gắn Lịch Sử" đã đăng chờ CEO duyệt.
--   * CEO "duyệt AUTO" → chạy bulk cả nhóm chắc chắn: 66/66 tên, 220
--     dòng, 443,3tr gắn xong (2 dòng phim Instax là hàng BÁN cần biến
--     thể 10/20 tấm, vá tay ngay sau đó). Ghi chú mỗi dòng có đuôi
--     "[duyệt AUTO 2026-08-21]" để truy vết. Sau đợt này còn 1.916 dòng
--     / 625 tên / 1,39 tỷ (nhóm cần chọn + không có SP + bỏ qua).
